<template><div><p>Hello there! 👋🏾 Welcome to the Node.js documentation! Let's get you started on how to navigate through this resource.</p>
<h2 id="how-to-use-this-guide" tabindex="-1"><a class="header-anchor" href="#how-to-use-this-guide"><span>How to Use This Guide</span></a></h2>
<h3 id="guides" tabindex="-1"><a class="header-anchor" href="#guides"><span>Guides</span></a></h3>
<p>In the <RouteLink to="/get-started/">Get started</RouteLink> section, you'll find helpful guides to assist you in your Node.js journey. Whether you're looking to install Node.js, get started quickly with running your first application, or understand the core concepts of Node.js, you'll find everything you need here.</p>
<ul>
<li><strong><RouteLink to="/get-started/installation.html">Installation Guides</RouteLink></strong>: Need help setting up Node.js on your system? This guide has got you covered with step-by-step instructions.</li>
<li><strong><RouteLink to="/get-started/quick-start.html">Quick Start</RouteLink></strong>: Dive right into coding with Node.js! This quick start guide will have you up and running with your first Node.js application in no time.</li>
<li><strong><RouteLink to="/get-started/what-is-nodejs.html">Understanding Node.js</RouteLink></strong>: Curious about what Node.js is and how it works? This guide provides a straightforward explanation of the core concepts behind Node.js.</li>
</ul>
<h3 id="docs" tabindex="-1"><a class="header-anchor" href="#docs"><span>Docs</span></a></h3>
<p>In the <RouteLink to="/docs/">Docs</RouteLink> section, you'll find detailed explanations of the fundamental concepts of Node.js. Whether you're interested in learning about Node.js modules, file system operations, or events, you'll find everything you need here.</p>
<h3 id="examples" tabindex="-1"><a class="header-anchor" href="#examples"><span>Examples</span></a></h3>
<p>This course is structured to help you learn Node.js by doing. Under each concept in the <RouteLink to="/docs/">Docs</RouteLink> section, you'll find examples that demonstrate how to apply the concepts in practice. The examples will look like this:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> http <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'http'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

http<span class="token punctuation">.</span><span class="token function">createServer</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">req<span class="token punctuation">,</span> res</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  res<span class="token punctuation">.</span><span class="token function">writeHead</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token string-property property">'Content-Type'</span><span class="token operator">:</span> <span class="token string">'text/plain'</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  res<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token string">'Hello World!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">listen</span><span class="token punctuation">(</span><span class="token number">8080</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>There are also some types of examples that you'll need to run via the command line. These examples will look like this:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code>console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'This example is different!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'The result is displayed in the Command Line Interface'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>And that's it! You're all set to start your Node.js journey. If you have any questions or need help, feel free to reach out to us on <a href="https://twitter.com/nodejs" target="_blank" rel="noopener noreferrer">Twitter<ExternalLinkIcon/></a> or <a href="https://github.com/nodejs/help" target="_blank" rel="noopener noreferrer">GitHub<ExternalLinkIcon/></a> - we're here to help! 🚀</p>
</div></template>


