<template><div><p>NPM, short for Node Package Manager, is a package manager designed specifically for Node.js packages or modules. It serves as a central repository where you can find and download thousands of free packages to use in your Node.js projects. You can explore available packages at <a href="https://www.npmjs.com/" target="_blank" rel="noopener noreferrer">www.npmjs.com<ExternalLinkIcon/></a>.</p>
<p>The NPM program comes pre-installed on your computer when you install Node.js, making it readily available for use without any additional setup.</p>
<h2 id="what-is-a-package" tabindex="-1"><a class="header-anchor" href="#what-is-a-package"><span>What is a Package?</span></a></h2>
<p>In the context of Node.js, a package contains all the files necessary for a module. Modules are JavaScript libraries that you can include and utilize within your projects.</p>
<h2 id="download-a-package" tabindex="-1"><a class="header-anchor" href="#download-a-package"><span>Download a Package</span></a></h2>
<p>Downloading a package using NPM is straightforward. Simply open your command line interface and instruct NPM to download the desired package. For example, to download a package named &quot;upper-case&quot;, you would use the following command:</p>
<div class="language-bash line-numbers-mode" data-ext="sh" data-title="sh"><pre v-pre class="language-bash"><code>C:<span class="token punctuation">\</span>Users<span class="token punctuation">\</span>Your Name<span class="token operator">></span>npm <span class="token function">install</span> upper-case
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>This command will download and install the &quot;upper-case&quot; package onto your system. NPM creates a folder named &quot;node_modules&quot; where the downloaded package is placed. Any future packages you install will also be stored in this folder.</p>
<h2 id="using-a-package" tabindex="-1"><a class="header-anchor" href="#using-a-package"><span>Using a Package</span></a></h2>
<p>Once the package is installed, you can easily include it in your Node.js files just like any other module. For instance, to use the &quot;upper-case&quot; package, you would include it in your file as follows:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> uc <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'upper-case'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Now, you can utilize the functionalities provided by the &quot;upper-case&quot; package in your code. Here's an example of creating a Node.js file that converts the output &quot;Hello World!&quot; into uppercase letters using the &quot;upper-case&quot; package:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token comment">// demo_uppercase.js</span>

<span class="token keyword">var</span> http <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'http'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> uc <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'upper-case'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

http<span class="token punctuation">.</span><span class="token function">createServer</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">req<span class="token punctuation">,</span> res</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  res<span class="token punctuation">.</span><span class="token function">writeHead</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token string-property property">'Content-Type'</span><span class="token operator">:</span> <span class="token string">'text/html'</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  res<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>uc<span class="token punctuation">.</span><span class="token function">upperCase</span><span class="token punctuation">(</span><span class="token string">"Hello World!"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  res<span class="token punctuation">.</span><span class="token function">end</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">listen</span><span class="token punctuation">(</span><span class="token number">8080</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Save the above code in a file named &quot;demo_uppercase.js&quot; and execute it in your command line interface:</p>
<div class="language-bash line-numbers-mode" data-ext="sh" data-title="sh"><pre v-pre class="language-bash"><code>C:<span class="token punctuation">\</span>Users<span class="token punctuation">\</span>Your Name<span class="token operator">></span>node demo_uppercase.js
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div></div></template>


